name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself

jobs:
  job1:
    name: Mesheryctl Pattern Actions
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl pattern action
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
        with:
          provider_token: ${{ secrets.PROVIDER_TOKEN }}
          platform: docker
          service_mesh: istio
          url: https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern.yaml
