name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "Meshery auth token"
        required: true

jobs:
  job1:
    name: Mesheryctl Pattern Action
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl pattern action
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
        with:
          provider_token: ${{ secrets.PROVIDER_TOKEN }}
          platform: docker
          url: https://raw.githubusercontent.com/service-mesh-patterns/service-mesh-patterns/master/samples/IstioFilterPattern.yaml
